version: "3"
services:
  ilab-selenium:
    restart: always
    container_name: ilab-selenium
    hostname: ilab-selenium
    image: selenium/hub:4.1.2-20220208
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    networks:
      - ilab-net

  selenium-chrome:
    restart: always
    container_name: selenium-chrome
    hostname: selenium-chrome
    image: selenium/node-chrome:4.1.2-20220208
    shm_size: 2gb
    depends_on:
      - ilab-selenium
    environment:
      SE_EVENT_BUS_HOST: ilab-selenium
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_HOST: selenium-chrome
      SE_NODE_OVERRIDE_MAX_SESSIONS: true
      SE_NODE_MAX_SESSIONS: 5
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5900:5900
    networks:
      - ilab-net

  selenium-firefox:
    restart: always
    container_name: selenium-firefox
    hostname: selenium-firefox
    image: selenium/node-firefox:4.1.2-20220208
    shm_size: 2gb
    depends_on:
      - ilab-selenium
    environment:
      SE_EVENT_BUS_HOST: ilab-selenium
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_HOST: selenium-firefox
      SE_NODE_OVERRIDE_MAX_SESSIONS: true
      SE_NODE_MAX_SESSIONS: 5
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5901:5900
    networks:
      - ilab-net

  selenium-edge:
    restart: always
    container_name: selenium-edge
    hostname: selenium-edge
    image: selenium/node-edge:4.1.2-20220208
    shm_size: 2gb
    depends_on:
      - ilab-selenium
    environment:
      SE_EVENT_BUS_HOST: ilab-selenium
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_HOST: selenium-edge
      SE_NODE_OVERRIDE_MAX_SESSIONS: true
      SE_NODE_MAX_SESSIONS: 5
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5902:5900
    networks:
      - ilab-net

networks:
  ilab-net:
    name: ilab-net